#ifndef _I2C_INTERFACE_INTERNAL_H_
#define _I2C_INTERFACE_INTERNAL_H_

#include <stdint.h>

#ifndef F_CPU
#define F_CPU 16000000L
#endif

#define I2C_BIT_WRITE 0
#define I2C_BIT_READ 1
#define I2C_BIT_ENABLE 2
#define I2C_BIT_STOP 4
#define I2C_BIT_START 5
#define I2C_BIT_ENABLE_ACK 6
#define I2C_BIT_INT 7
#define I2C_BIT_REPEATED_START 0x10

#define I2C_STATUS_START 0x08
#define I2C_STATUS_REPEATED_START 0x10
#define I2C_STATUS_SLAVE_WRITE_ACK_RECEIVED 0x18
#define I2C_STATUS_SLAVE_READ_ACK_RECEIVED 0x40
#define I2C_STATUS_DATA_TRANSMIT_ACK_RECEIVED 0x28
#define I2C_STATUS_DATA_READ_ACK_SENT 0x50
#define I2C_STATUS_DATA_READ_NACK_SENT 0x58



#endif /* _I2C_INTERFACE_INTERNAL_H_ */
